### ISSUE TITLE
Error : nsPositiveControlNormalization(nano)

### ISSUE THREAD

**Issue by athulmenon** [KevinMenden/nanoR#1]
Hi,

I am facing an error below when running nsPositiveControlNormalization(nano) with one RCC file.

> nano <- nsPositiveControlNormalization(nano)
Error in apply(X = pos.counts, MARGIN = 2, FUN = pcm) : 
  dim(X) must have a positive length

Can you please let me know what is the issue?

Athul

**Comment by KevinMenden** [comment]
Hi Athul,

one RCC file meaning only one sample?
The problem is that X - which is your gene expression matrix, apparently is not a matrix, but just a vector, since you only have one RCC file.

If it's only one sample you don't have to normalize. Have you tried it with all of your samples?

**Comment by athulmenon** [comment]
Dear Kevin,

Thank you for quick reply.
The problem was solved when I placed 3 of my RCC files. But now I am facing an issue with the groups. I created the groups with the command below.
groups <- c("G1","G2","G3")
and tried to run plotNormDistanceRatio(nano, groups) but it gives the following error.

> plotNormDistanceRatio(nano, groups)
Error in d.glob[, !grepl(g, colnames(d.glob))] : 
  incorrect number of dimensions

Can you please help in this. I am new to R. Thanks in advance.

Regards,
Athul

**Comment by KevinMenden** [comment]
Hi Athul,

That's bit more tricky, but from a quick look at the code I think it is because you have three samples and three groups. I'm sorry that there are no good warnings in this package, that's something I probably should include.

Basically if you have only one sample per group, you cannot plot the norm distance ratio, because it calculater inner group distance and global distance for comparison. Basically, only 1 sample per group is generally not a good idea because you cannot do any statistical analysis with it.

I would suggest you use all of your samples (RCC files) at once, and assign them with meaningful groups. Then you can also use this plot function. Most of the functionality of this package won't work with one-sample-groups.

Hope that helps!
Cheers,
Kevin
